# Generated by Django 5.2.1 on 2025-05-21 23:38

import veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'CHEVROLET - GM'), (4, 'FERRARI'), (5, 'FIAT'), (6, 'FORD'), (7, 'HONDA'), (8, 'HYUNDAI'), (9, 'VOLKSWAGEN')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField(validators=[veiculos.models.validate_ano])),
                ('cor', models.SmallIntegerField(blank=True, choices=[(1, 'BRANCO'), (2, 'AMARELO'), (3, 'AZUL'), (4, 'PRATA'), (5, 'PRETO'), (6, 'VERMELHO')], null=True)),
                ('combustivel', models.SmallIntegerField(blank=True, choices=[(1, 'ETANOL'), (2, 'DIESEL'), (3, 'FLEX'), (4, 'GASOLINA')], null=True)),
                ('preco_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='veiculos_fotos/')),
            ],
            options={
                'db_table': 'veiculos_veiculo',
            },
        ),
    ]
